In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()
x = iris.data
y = iris.target

In [3]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [4]:
from sklearn.neural_network import MLPClassifier

model = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [5]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [6]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

1.0
